@apiUrl = http://localhost:3001/api

###

# @name getBlogs
GET {{apiUrl}}/blogs

###

# @name postBlog
POST {{apiUrl}}/blogs
Content-Type: application/json

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2
}

###

# @name getBlog
@blogId = {{getBlogs.response.body.0.id}}
PUT {{apiUrl}}/blogs/{{blogId}}

###

# @name likeBlog
@blogId = {{getBlogs.response.body.0.id}}
POST {{apiUrl}}/blogs/like/{{blogId}}
